name: Update Example Image

on:
    schedule:
        # Run every 6 hours
        - cron: '0 */6 * * *'
    workflow_dispatch: # Allow manual triggering

permissions:
    contents: write
    pull-requests: write

jobs:
    update-example:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: latest

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build project
              run: pnpm build

            - name: Run project to generate output
              run: pnpm start

            - name: Update example image
              run: cp output.png example.png

            - name: Create Pull Request for changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add example.png
                  if git diff --staged --quiet; then
                    echo "No changes to commit"
                  else
                    # Create a unique branch name with timestamp
                    BRANCH_NAME="update-example-$(date +%Y%m%d-%H%M%S)"
                    git checkout -b "$BRANCH_NAME"
                    git commit -m "Updated the example image"
                    git push origin "$BRANCH_NAME"
                    
                    # Create pull request using GitHub CLI
                    gh pr create \
                      --title "Update example image (automated)" \
                      --body "Automated update of example.png generated from the latest code." \
                      --base main \
                      --head "$BRANCH_NAME"
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
